### ISSUE TITLE
detials view in generated app not showing correct info

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#114]
When I select a grid recorded and then click view, the view detials page does not show any data for  the record and the dependent grid info on that page is wrong too. 

![screen shot 2016-10-31 at 2 34 31 pm](https://cloud.githubusercontent.com/assets/3607052/19847189/af289084-9f77-11e6-8aa0-d41a4b8bebf8.png)
![screen shot 2016-10-31 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/3607052/19847190/af297a1c-9f77-11e6-9e4e-f064d698103e.png)

**Comment by wongpratan** [comment]
Fixed filter linked object in Grid - https://github.com/appdevdesigns/app_builder/commit/034910c798a9060b4b31bb9947ff819c1b1f5618

Fixed UI size of view component - 
https://github.com/appdevdesigns/app_builder/commit/9836a814cba41435401004f402cc5063d74b1f85

**Comment by appdevdesigns** [comment]
I just updated my local code and tried this out. The view record info is showing but the grid that should be filtered by it is still showing all records. 

Below, I have selected rec Obj1.test2 but Obj1.test1 records are showing in Obj2 list

![screen shot 2016-10-31 at 5 06 05 pm](https://cloud.githubusercontent.com/assets/3607052/19850747/c368b14a-9f8c-11e6-9d1e-5479e4eae65e.png)

**Comment by appdevdesigns** [comment]
all the above seems fixed now. However, the grid based on the selected record still does not get refreshed when the user comes back to the page after adding a new item which issue #120 . 
So we can close this now.
