### ISSUE TITLE
date fields still getting NanNan

### ISSUE THREAD

**Issue by appdevdesigns** [appdevdesigns/appdev-opsportal#163]
it may be dates added in the object builder or not showing properly in the runtime app. Or it could be something else but there is a problem. 

<img width="650" alt="screen shot 2016-11-24 at 9 51 40 pm" src="https://cloud.githubusercontent.com/assets/3607052/20603513/6745ad30-b294-11e6-8e4b-de5c37b755f1.png">

<img width="527" alt="screen shot 2016-11-24 at 10 15 21 pm" src="https://cloud.githubusercontent.com/assets/3607052/20603528/7c74bac0-b294-11e6-9b92-ec1918838278.png">

**Comment by wongpratan** [comment]
Fixed - https://github.com/appdevdesigns/app_builder/commit/0df18f29d245ce0abd01905738bf29fa1ae6e22b

**Comment by appdevdesigns** [comment]
The date issue is not fixed yet. See [this](https://www.dropbox.com/s/5njhidpx4n48p4e/Kapture%202016-12-14%20at%2013.42.45.mp4?dl=0)
